fix rvalue reference error
AnthonyCalandra/modern-cpp-features pull request #89
Opened 2020-10-10 08:29 UTC by raphael10241024

some tiny error here.
When T&& meets` int&`, T becomes `int&`. When T&& meets `int&&`, T becomes `int`  in fact, not `int &&`.
see https://en.cppreference.com/w/cpp/utility/forward.

2020-10-10 16:15 UTC, AnthonyCalandra commented
Nice, this definitely looks like a bug. Could you also make the same change to README.md before I approve?

2020-10-12 06:47 UTC, raphael10241024 commented
submitted

2020-10-12 17:31 UTC, AnthonyCalandra requested changes

2020-10-12 17:31 UTC, AnthonyCalandra commented on CPP11.md
> +int&& xr2 = 0; // `xr2` is an rvalue of type `int&&` -- binds to the rvalue temporary, `0`
This comment change isn't correct. `xr2` is still an lvalue, but its type is `int&&`.

2020-10-12 17:31 UTC, AnthonyCalandra commented on CPP11.md
> +f(xr2);           // calss f(int&)
calls*

2020-10-12 17:31 UTC, AnthonyCalandra commented on CPP11.md
> +void f(int&& x){}
Add a space between the closing parens and opening braces.

2020-10-12 17:31 UTC, AnthonyCalandra commented on CPP11.md
> +int&& z = 0; // NOTE: `z` is an rvalue, but it becomes lvalue when we use it in expressions.
Same as above; `z` is an lvalue.

2020-10-12 17:31 UTC, AnthonyCalandra commented on README.md
> +int&& z = 0; // NOTE: `z` is an rvalue, but it becomes lvalue when we use it in expressions.
Same as above; `z` is an lvalue.

2020-10-12 17:41 UTC, AnthonyCalandra commented
Here's a reference to my claims: http://eel.is/c++draft/basic.lval#4
>  In general, the effect of this rule is that **named rvalue references are treated as lvalues** and unnamed rvalue references to objects are treated as xvalues; rvalue references to functions are treated as lvalues whether named or not.
— end note
The example with the named rvalue reference `ar` is also noted as an lvalue.

2020-10-12 17:44 UTC, AnthonyCalandra commented on README.md
> +f(xr2);           // calss f(int&)
calls*

2020-10-13 03:29 UTC, AnthonyCalandra approved these changes
LGTM, thanks for the fix.

2020-10-13 03:30 UTC, merged